name: Build

on:
  push:
    branches: ["*"]
    paths-ignore:
      - README.md
      - resources
  pull_request:
    branches: ["*"]
    paths-ignore:
      - README.md
      - resources
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - name: Install Python
        run: sudo apt-get -y install python
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Build ds-ramview
        run: make
      - name: Upload ds-ramview.nds
        uses: actions/upload-artifact@v2
        with:
          name: ds-ramview.nds
          path: ds-ramview.nds
